server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-all
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health
